env:
  es2021: true
  node: true
extends:
  - airbnb-base
  - plugin:import/recommended
  - plugin:import/errors
  - plugin:import/warnings
parserOptions:
  ecmaVersion: 13
  sourceType: module
rules:
  indent: ["error", 2]
  camelcase: off
  no-console: off
  no-await-in-loop: off
  import/extensions: off
  max-len: ["error", { code: 120, ignoreComments: true, ignoreTemplateLiterals: true }]
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
